categories:
   consumables:
      - APPLE
      - BAKED_POTATO
      - BEEF
      - BEETROOT
      - BEETROOT_SOUP
      - BREAD
      - CAKE
      - CARROT
      - COD
      - COOKED_BEEF
      - COOKED_CHICKEN
      - COOKED_COD
      - COOKED_MUTTON
      - COOKED_PORKCHOP
      - COOKED_RABBIT
      - COOKED_SALMON
      - COOKIE
      - DRIED_KELP
      - ENCHANTED_GOLDEN_APPLE
      - GLISTERING_MELON_SLICE
      - GOLDEN_APPLE
      - GOLDEN_CARROT
      - LINGERING_POTION
      - MELON_SLICE
      - MILK_BUCKET
      - MUSHROOM_STEW
      - MUTTON
      - POSIONOUS_POTATO
      - PORKCHOP
      - POTATO
      - POTION
      - PUFFERFISH
      - PUMPKIN_PIE
      - RABBIT
      - RABBIT_STEW
      - ROTTEN_FLESH
      - SALMON
      - SPIDER_EYE
      - SPLASH_POTION
      - TROPICAL_FISH
   armors:
      - CHAINMAIL_BOOTS
      - CHAINMAIL_CHESTPLATE
      - CHAINMAIL_HELMET
      - CHAINMAIL_LEGGINGS
      - DIAMOND_BOOTS
      - DIAMOND_CHESTPLATE
      - DIAMOND_HELMET
      - DIAMOND_LEGGINGS
      - GOLDEN_BOOTS
      - GOLDEN_CHESTPLATE
      - GOLDEN_HELMET
      - GOLDEN_LEGGINGS
      - IRON_BOOTS
      - IRON_CHESTPLATE
      - IRON_HELMET
      - IRON_LEGGINGS
      - LEATHER_BOOTS
      - LEATHER_CHESTPLATE
      - LEATHER_HELMET
      - LEATHER_LEGGINGS
      - SHIELD
      - TURTLE_HELMET
   weapons:
      - ARROW
      - BOW
      - DIAMOND_AXE
      - DIAMOND_SWORD
      - GOLDEN_AXE
      - GOLDEN_SWORD
      - IRON_AXE
      - IRON_SWORD
      - SPECTRAL_ARROW
      - STONE_AXE
      - STONE_SWORD
      - TIPPED_ARROW
      - TRIDENT
      - WOODEN_AXE
      - WOODEN_SWORD
   tools:
      - BUCKET
      - CARROT_ON_A_STICK
      - CLOCK
      - COMPASS
      - DIAMOND_AXE
      - DIAMOND_HOE
      - DIAMOND_HORSE_ARMOR
      - DIAMOND_PICKAXE
      - DIAMOND_SHOVEL
      - FISHING_ROD
      - FLINT_AND_STEEL
      - GOLDEN_AXE
      - GOLDEN_HOE
      - GOLDEN_HORSE_ARMOR
      - GOLDEN_PICKAXE
      - GOLDEN_SHOVEL
      - IRON_AXE
      - IRON_HOE
      - IRON_HORSE_ARMOR
      - IRON_PICKAXE
      - IRON_SHOVEL
      - LAVA_BUCKET
      - LEAD
      - MAP
      - SADDLE
      - SHEARS
      - SPONGE
      - STONE_AXE
      - STONE_HOE
      - STONE_PICKAXE
      - STONE_SHOVEL
      - TNT
      - TOTEM_OF_UNDYING
      - WATER_BUCKET
      - WET_SPONGE
      - WOODEN_AXE
      - WOODEN_HOE
      - WOODEN_PICKAXE
      - WOODEN_SHOVEL
   blocks:
      - ACACIA_DOOR
      - ACACIA_FENCE
      - ACACIA_FENCE_GATE
      - ACACIA_LEAVES
      - ACACIA_LOG
      - ACACIA_PLANKS
      - ACACIA_SLAB
      - ACACIA_STAIRS
      - ACACIA_TRAPDOOR
      - ACACIA_WOOD
      - ANDESITE
      - ANVIL
      - BEACON
      - BIRCH_DOOR
      - BIRCH_FENCE
      - BIRCH_FENCE_GATE
      - BIRCH_LEAVES
      - BIRCH_LOG
      - BIRCH_PLANKS
      - BIRCH_SLAB
      - BIRCH_STAIRS
      - BIRCH_TRAPDOOR
      - BIRCH_WOOD
      - BLACK_BED
      - BLACK_CARPET
      - BLACK_CONCRETE
      - BLACK_CONCRETE_POWDER
      - BLACK_GLAZED_TERRACOTTA
      - BLACK_STAINED_GLASS
      - BLACK_STAINED_GLASS_PANE
      - BLACK_TERRACOTTA
      - BLACK_WOOL
      - BLUE_BED
      - BLUE_CARPET
      - BLUE_CONCRETE
      - BLUE_CONCRETE_POWDER
      - BLUE_GLAZED_TERRACOTTA
      - BLUE_ICE
      - BLUE_STAINED_GLASS
      - BLUE_STAINED_GLASS_PANE
      - BLUE_TERRACOTTA
      - BLUE_WOOL
      - BONE_BLOCK
      - BOOKSHELF
      - BRAIN_CORAL
      - BRAIN_CORAL_BLOCK
      - BRAIN_CORAL_FAN
      - BRAIN_CORAL_WALL_FAN
      - BREWING_STAND
      - BRICKS
      - BRICK_SLAB
      - BRICK_STAIRS
      - BROWN_BED
      - BROWN_CONCRETE
      - BROWN_CONCRETE_POWDER
      - BROWN_GLAZED_TERRACOTTA
      - BROWN_MUSHROOM_BLOCK
      - BROWN_STAINED_GLASS
      - BROWN_STAINED_GLASS_PANE
      - BROWN_TERRACOTTA
      - BROWN_WOOL
      - BUBBLE_CORAL
      - BUBBLE_CORAL_BLOCK
      - BUBBLE_CORAL_FAN
      - BUBBLE_CORAL_WALL_FAN
      - CACTUS
      - CARVED_PUMPKIN
      - CAULDRON
      - CHEST
      - CHIPPED_ANVIL
      - CHISELED_QUARTZ_BLOCK
      - CHISELED_RED_SANDSTONE
      - CHISELED_SANDSTONE
      - CHISELED_STONE_BRICKS
      - CLAY
      - COAL_BLOCK
      - COAL_ORE
      - COARSE_DIRT
      - COBBLESTONE
      - COBBLESTONE_SLAB
      - COBBLESTONE_STAIRS
      - COBBLESTONE_WALL
      - COBWEB
      - CONDUIT
      - CRACKED_STONE_BRICKS
      - CRAFTING_TABLE
      - CUT_RED_SANDSTONE
      - CUT_SANDSTONE
      - CYAN_BED
      - CYAN_CARPET
      - CYAN_CONCRETE
      - CYAN_CONCRETE_POWDER
      - CYAN_GLAZED_TERRACOTTA
      - CYAN_STAINED_GLASS
      - CYAN_STAINED_GLASS_PANE
      - CYAN_TERRACOTTA
      - CYAN_WOOL
      - DAMAGED_ANVIL
      - DARK_OAK_DOOR
      - DARK_OAK_FENCE
      - DARK_OAK_FENCE_GATE
      - DARK_OAK_LEAVES
      - DARK_OAK_LOG
      - DARK_OAK_PLANKS
      - DARK_OAK_SLAB
      - DARK_OAK_STAIRS
      - DARK_OAK_TRAPDOOR
      - DARK_OAK_WOOD
      - DARK_PRISMARINE
      - DARK_PRISMARINE_SLAB
      - DARK_PRISMARINE_STAIRS
      - DEAD_BRAIN_CORAL
      - DEAD_BRAIN_CORAL_BLOCK
      - DEAD_BRAIN_CORAL_FAN
      - DEAD_BRAIN_CORAL_WALL_FAN
      - DEAD_BUBBLE_CORAL
      - DEAD_BUBBLE_CORAL_BLOCK
      - DEAD_BUBBLE_CORAL_FAN
      - DEAD_BUBBLE_CORAL_WALL_FAN
      - DEAD_BUSH
      - DEAD_FIRE_CORAL
      - DEAD_FIRE_CORAL_BLOCK
      - DEAD_FIRE_CORAL_FAN
      - DEAD_FIRE_CORAL_WALL_FAN
      - DEAD_HORN_CORAL
      - DEAD_HORN_CORAL_BLOCK
      - DEAD_HORN_CORAL_FAN
      - DEAD_HORN_CORAL_WALL_FAN
      - DEAD_TUBE_CORAL
      - DEAD_TUBE_CORAL_BLOCK
      - DEAD_TUBE_CORAL_FAN
      - DEAD_TUBE_CORAL_WALL_FAN
      - DIAMOND_BLOCK
      - DIAMOND_ORE
      - DIORITE
      - DIRT
      - DRIED_KELP_BLOCK
      - EMERALD_BLOCK
      - EMERALD_ORE
      - ENCHANTING_TABLE
      - ENDER_CHEST
      - END_ROD
      - END_STONE
      - END_STONE_BRICKS
      - FIRE_CORAL
      - FIRE_CORAL_BLOCK
      - FIRE_CORAL_FAN
      - FIRE_CORAL_WALL_FAN
      - FLOWER_POT
      - FROSTED_ICE
      - FURNACE
      - GLASS
      - GLASS_PANE
      - GLOWSTONE
      - GOLD_BLOCK
      - GOLD_ORE
      - GRANITE
      - GRASS_BLOCK
      - GRAVEL
      - GRAY_BED
      - GRAY_CARPET
      - GRAY_CONCRETE
      - GRAY_CONCRETE_POWDER
      - GRAY_GLAZED_TERRACOTTA
      - GRAY_STAINED_GLASS
      - GRAY_STAINED_GLASS_PANE
      - GRAY_TERRACOTTA
      - GRAY_WOOL
      - GREEN_BED
      - GREEN_CARPET
      - GREEN_CONCRETE
      - GREEN_CONCRETE_POWDER
      - GREEN_GLAZED_TERRACOTTA
      - GREEN_STAINED_GLASS
      - GREEN_STAINED_GLASS_PANE
      - GREEN_TERRACOTTA
      - GREEN_WOOL
      - HAY_BLOCK
      - HORN_CORAL
      - HORN_CORAL_BLOCK
      - HORN_CORAL_FAN
      - HORN_CORAL_WALL_FAN
      - ICE
      - INFESTED_CHISELED_STONE_BRICKS
      - INFESTED_COBBLESTONE
      - INFESTED_CRACKED_STONE_BRICKS
      - INFESTED_MOSSY_STONE_BRICKS
      - INFESTED_STONE
      - INFESTED_STONE_BRICKS
      - IRON_BARS
      - IRON_BLOCK
      - IRON_DOOR
      - IRON_ORE
      - IRON_TRAPDOOR
      - ITEM_FRAME
      - JACK_O_LANTERN
      - JUKEBOX
      - JUNGLE_DOOR
      - JUNGLE_FENCE
      - JUNGLE_FENCE_GATE
      - JUNGLE_LEAVES
      - JUNGLE_LOG
      - JUNGLE_PLANKS
      - JUNGLE_SLAB
      - JUNGLE_STAIRS
      - JUNGLE_TRAPDOOR
      - JUNGLE_WOOD
      - LADDER
      - LAPIS_BLOCK
      - LAPIS_ORE
      - LIGHT_BLUE_BED
      - LIGHT_BLUE_CARPET
      - LIGHT_BLUE_CONCRETE
      - LIGHT_BLUE_CONCRETE_POWDER
      - LIGHT_BLUE_GLAZED_TERRACOTTA
      - LIGHT_BLUE_STAINED_GLASS
      - LIGHT_BLUE_STAINED_GLASS_PANE
      - LIGHT_BLUE_TERRACOTTA
      - LIGHT_BLUE_WOOL
      - LIGHT_GRAY_BED
      - LIGHT_GRAY_CARPET
      - LIGHT_GRAY_CONCRETE
      - LIGHT_GRAY_CONCRETE_POWDER
      - LIGHT_GRAY_GLAZED_TERRACOTTA
      - LIGHT_GRAY_STAINED_GLASS
      - LIGHT_GRAY_STAINED_GLASS_PANE
      - LIGHT_GRAY_TERRACOTTA
      - LIGHT_GRAY_WOOL
      - LIME_BED
      - LIME_CARPET
      - LIME_CONCRETE
      - LIME_CONCRETE_POWDER
      - LIME_GLAZED_TERRACOTTA
      - LIME_STAINED_GLASS
      - LIME_STAINED_GLASS_PANE
      - LIME_TERRACOTTA
      - LIME_WOOL
      - MAGENTA_BED
      - MAGENTA_CARPET
      - MAGENTA_CONCRETE
      - MAGENTA_CONCRETE_POWDER
      - MAGENTA_GLAZED_TERRACOTTA
      - MAGENTA_STAINED_GLASS
      - MAGENTA_STAINED_GLASS_PANE
      - MAGENTA_TERRACOTTA
      - MAGENTA_WOOL
      - MAGMA_BLOCK
      - MOSSY_COBBLESTONE
      - MOSSY_COBBLESTONE_WALL
      - MOSSY_STONE_BRICKS
      - MUSHROOM_STEM
      - MYCELIUM
      - NETHERRACK
      - NETHER_BRICKS
      - NETHER_BRICK_FENCE
      - NETHER_BRICK_SLAB
      - NETHER_BRICK_STAIRS
      - NETHER_QUARTZ_ORE
      - NETHER_WART_BLOCK
      - NOTE_BLOCK
      - OAK_DOOR
      - OAK_FENCE
      - OAK_FENCE_GATE
      - OAK_LEAVES
      - OAK_LOG
      - OAK_PLANKS
      - OAK_SLAB
      - OAK_STAIRS
      - OAK_TRAPDOOR
      - OAK_WOOD
      - OBSIDIAN
      - ORANGE_BED
      - ORANGE_CARPET
      - ORANGE_CONCRETE
      - ORANGE_CONCRETE_POWDER
      - ORANGE_GLAZED_TERRACOTTA
      - ORANGE_STAINED_GLASS
      - ORANGE_STAINED_GLASS_PANE
      - ORANGE_TERRACOTTA
      - ORANGE_WOOL
      - PACKED_ICE
      - PINK_BED
      - PINK_CARPET
      - PINK_CONCRETE
      - PINK_CONCRETE_POWDER
      - PINK_GLAZED_TERRACOTTA
      - PINK_STAINED_GLASS
      - PINK_STAINED_GLASS_PANE
      - PINK_TERRACOTTA
      - PINK_WOOL
      - PODZOL
      - POLISHED_ANDESITE
      - POLISHED_DIORITE
      - POLISHED_GRANITE
      - PRISMARINE
      - PRISMARINE_BRICKS
      - PRISMARINE_BRICK_SLAB
      - PRISMARINE_BRICK_STAIRS
      - PRISMARINE_SLAB
      - PRISMARINE_STAIRS
      - PURPLE_BED
      - PURPLE_CARPET
      - PURPLE_CONCRETE
      - PURPLE_CONCRETE_POWDER
      - PURPLE_GLAZED_TERRACOTTA
      - PURPLE_STAINED_GLASS
      - PURPLE_STAINED_GLASS_PANE
      - PURPLE_TERRACOTTA
      - PURPLE_WOOL
      - PURPUR_BLOCK
      - PURPUR_PILLAR
      - PURPUR_SLAB
      - PURPUR_STAIRS
      - QUARTZ_BLOCK
      - QUARTZ_PILLAR
      - QUARTZ_SLAB
      - QUARTZ_STAIRS
      - RAIL
      - REDSTONE_BLOCK
      - REDSTONE_ORE
      - RED_BED
      - RED_CARPET
      - RED_CONCRETE
      - RED_CONCRETE_POWDER
      - RED_GLAZED_TERRACOTTA
      - RED_MUSHROOM_BLOCK
      - RED_NETHER_BRICKS
      - RED_SAND
      - RED_SANDSTONE
      - RED_SANDSTONE_SLAB
      - RED_SANDSTONE_STAIRS
      - RED_STAINED_GLASS
      - RED_STAINED_GLASS_PANE
      - RED_TERRACOTTA
      - RED_WOOL
      - SAND
      - SANDSTONE
      - SANDSTONE_SLAB
      - SANDSTONE_STAIRS
      - SEA_LANTERN
      - SIGN
      - SLIME_BLOCK
      - SMOOTH_QUARTZ
      - SMOOTH_RED_SANDSTONE
      - SMOOTH_SANDSTONE
      - SMOOTH_STONE
      - SNOW_BLOCK
      - SOUL_SAND
      - SPONGE
      - SPRUCE_DOOR
      - SPRUCE_FENCE
      - SPRUCE_FENCE_GATE
      - SPRUCE_LEAVES
      - SPRUCE_LOG
      - SPRUCE_PLANKS
      - SPRUCE_SLAB
      - SRPUCE_STAIRS
      - SPRUCE_TRAPDOOR
      - SPRUCE_WOOD
      - STONE
      - STONE_BRICKS
      - STONE_BRICK_SLAB
      - STONE_BRICK_STAIRS
      - STONE_SLAB
      - STRIPPED_ACACIA_LOG
      - STRIPPED_ACACIA_WOOD
      - STRIPPED_BIRCH_LOG
      - STRIPPED_BIRCH_WOOD
      - STRIPPED_DARK_OAK_LOG
      - STRIPPED_DARK_OAK_WOOD
      - STRIPPED_JUNGLE_LOG
      - STRIPPED_JUNGLE_WOOD
      - STRIPPED_OAK_LOG
      - STRIPPED_OAK_WOOD
      - STRIPPED_SPRUCE_LOG
      - STRIPPED_SPRUCE_WOOD
      - TERRACOTTA
      - TNT
      - TORCH
      - TUBE_CORAL
      - TUBE_CORAL_BLOCK
      - TUBE_CORAL_FAN
      - TUBE_CORAL_WALL_FAN
      - VINE
      - WET_SPONGE
      - WHITE_BED
      - WHITE_CARPET
      - WHITE_CONCRETE
      - WHITE_CONCRETE_POWDER
      - WHITE_GLAZED_TERRACTTA
      - WHITE_STAINED_GLASS
      - WHITE_STAINED_GLASS_PANE
      - WHITE_TERRACOTTA
      - WHITE_WOOL
      - YELLOW_BED
      - YELLOW_CARPET
      - YELLOW_CONCRETE
      - YELLOW_CONCRETE_POWDER
      - YELLOW_GLAZED_TERRACOTTA
      - YELLOW_STAINED_GLASS
      - YELLOW_STAINED_GLASS_PANE
      - YELLOW_TERRACOTTA
      - YELLOW_WOOL
   books:
      - BOOK
      - BOOKSHELF
      - ENCHANTED_BOOK
      - KNOWLEGE_BOOK
      - WRITABLE_BOOK
      - WRITTEN_BOOK
   resources:
      - COAL
      - COAL_BLOCK
      - COAL_ORE
      - DIAMOND
      - DIAMOND_BLOCK
      - DIAMOND_ORE
      - EMERALD
      - EMERALD_BLOCK
      - EMERALD_ORE
      - FLINT
      - GOLD_BLOCK
      - GOLD_INGOT
      - GOLD_NUGGET
      - GOLD_ORE
      - IRON_BLOCK
      - IRON_INGOT
      - IRON_NUGGET
      - IRON_ORE
      - LAPIS_BLOCK
      - LAPIS_LAZULI
      - LAPIS_ORE
      - LEATHER
      - NETHER_QUARTZ_ORE
      - PRISMARINE_CRYSTALS
      - PRISMARINE_SHARD
      - QUARTZ
      - RABBIT_HIDE
      - REDSTONE
      - REDSTONE_BLOCK
      - REDSTONE_ORE
   redstone:
      - ACACIA_BUTTON
      - ACACIA_DOOR
      - ACACIA_FENCE_GATE
      - ACACIA_PRESSURE_PLATE
      - ACACIA_TRAPDOOR
      - ACTIVATOR_RAIL
      - BIRCH_BUTTON
      - BIRCH_DOOR
      - BIRCH_FENCE_GATE
      - BIRCH_PRESSURE_PLATE
      - BIRCH_TRAPDOOR
      - COMPARATOR
      - DARK_OAK_BUTTON
      - DARK_OAK_DOOR
      - DARK_OAK_FENCE_GATE
      - DARK_OAK_PRESSURE_PLATE
      - DARK_OAK_TRAPDOOR
      - DAYLIGHT_DETECTOR
      - DETECTOR_RAIL
      - DISPENSER
      - DROPPER
      - HEAVY_WEIGHTED_PRESSURE_PLATE
      - HOPPER
      - HOPPER_MINECART
      - JUNGLE_BUTTON
      - JUNGLE_DOOR
      - JUNGLE_FENCE_GATE
      - JUNGLE_PRESSURE_PLATE
      - JUNGLE_TRAPDOOR
      - LEVER
      - LIGHT_WEIGHTED_PRESSURE_PLATE
      - NOTE_BLOCK
      - OAK_BUTTON
      - OAK_DOOR
      - OAK_FENCE_GATE
      - OAK_PRESSURE_PLATE
      - OAK_TRAPDOOR
      - OBSERVER
      - PISTON
      - POWERED_RAIL
      - REDSTONE
      - REDSTONE_BLOCK
      - REDSTONE_LAMP
      - REDSTONE_TORCH
      - REPEATER
      - SPRUCE_BUTTON
      - SPRUCE_DOOR
      - SPRUCE_FENCE_GATE
      - SPRUCE_PRESSURE_PLATE
      - SPRUCE_TRAPDOOR
      - STICKY_PISTON
      - STONE_BUTTON
      - STONE_PRESSURE_PLATE
      - TRAPPED_CHEST
      - TRIPWIRE_HOOK
   organics:
      - ACACIA_LEAVES
      - ACAICA_SAPLING
      - ALLIUM
      - AZURE_BLUET
      - BIRCH_LEAVES
      - BIRCH_SAPLING
      - BLUE_ORCHID
      - BRAIN_CORAL
      - BRAIN_CORAL_BLOCK
      - BRAIN_CORAL_FAN
      - BRAIN_CORAL_WALL_FAN
      - BROWN_MUSHROOM
      - BUBBLE_CORAL
      - BUBBLE_CORAL_BLOCK
      - BUBBLE_CORAL_FAN
      - BUBBLE_CORAL_WALL_FAN
      - CACTUS
      - DANDELION
      - DARK_OAK_LEAVES
      - DEAD_BRAIN_CORAL
      - DEAD_BRAIN_CORAL_BLOCK
      - DEAD_BRAIN_CORAL_FAN
      - DEAD_BRAIN_CORAL_WALL_FAN
      - DEAD_BUBBLE_CORAL
      - DEAD_BUBBLE_CORAL_BLOCK
      - DEAD_BUBBLE_CORAL_FAN
      - DEAD_BUBBLE_CORAL_WALL_FAN
      - DEAD_BUSH
      - DEAD_FIRE_CORAL
      - DEAD_FIRE_CORAL_BLOCK
      - DEAD_FIRE_CORAL_FAN
      - DEAD_FIRE_CORAL_WALL_FAN
      - DEAD_HORN_CORAL
      - DEAD_HORN_CORAL_BLOCK
      - DEAD_HORN_CORAL_FAN
      - DEAD_HORN_CORAL_WALL_FAN
      - DEAD_TUBE_CORAL
      - DEAD_TUBE_CORAL_BLOCK
      - DEAD_TUBE_CORAL_FAN
      - DEAD_TUBE_CORAL_WALL_FAN
      - FERN
      - FIRE_CORAL
      - FIRE_CORAL_BLOCK
      - FIRE_CORAL_FAN
      - FIRE_CORAL_WALL_FAN
      - GRASS
      - GRASS_BLOCK
      - HAY_BLOCK
      - HORN_CORAL
      - HORN_CORAL_BLOCK
      - HORN_CORAL_FAN
      - HORN_CORAL_WALL_FAN
      - JUNGLE_LEAVES
      - JUNGLE_SAPLING
      - KELP
      - LARGE_FERN
      - LILAC
      - LILY_PAD
      - MELON
      - NETHER_WART
      - NETHER_WART_BLOCK
      - OAK_LEAVES
      - OAK_SAPLING
      - ORANGE_TULIP
      - OXEYE_DAISY
      - PEONY
      - PINK_TULIP
      - POPPY
      - PUMPKIN
      - PUMPKIN_SEEDS
      - RED_MUSHROOM
      - RED_MUSHROOM_BLOCK
      - RED_TULIP
      - ROSE_BUSH
      - SEAGRASS
      - SEA_PICKLE
      - SUGAR_CANE
      - SUNFLOWER
      - TALL_GRASS
      - TALL_SEAGRASS
      - TUBE_CORAL
      - TUBE_CORAL_BLOCK
      - TUBE_CORAL_FAN
      - TUBE_CORAL_WALL_FAN
      - WHEAT
      - WHEAT_SEEDS
      - WHITE_TULIP

travelSpeed: 2
maxTimeInRecieval: 168
maxTimeAsListing: 168
worldDistance: 5000
maxStartFee: 30
maxAdTitleChars: 20
maxAdLoreLineChars: 20
maxAdLoreLines: 7
adExpireLimitHrs: 168
currencySuffix: 'g'